ITECH_Project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include

urlpatterns = [

    url(r'admin/', admin.site.urls),
    url(r'^', include(('product.urls', 'product'), namespace='products')),
    url(r'^user/', include(('user.urls', 'user'), namespace='user')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('order.urls', 'order'), namespace='order')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('allauth.urls')),

]

cart/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.user_cart, name="cart"),
    url(r'^add(\d+)_(\d+)/$', views.add, name="add"),
    url(r'^edit(\d+)_(\d+)/$', views.edit, name="edit"),
    url(r'^delete(\d+)/$', views.delete, name="delete"),
]

iCasa/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

product/urls.py
from django.conf.urls import url

from . import views

app_name = 'product'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.product_list, name="product_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.search, name="search"),
    url(r'^about/$', views.about, name="about"),
]

user/urls.py
from django.conf.urls import url

from .views import *

app_name = 'user'

urlpatterns = [
    # url(r'^register/$', register, name="register"),
    # url(r'^register_handle/$', register_handle, name="register_handle"),
    # url(r'^register_exist/$', register_exist, name="register_exist"),
    # url(r'^login/$', login, name="login"),
    # url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^myaccount/$', myaccount, name="myaccount"),
    # url(r'^profile/update/$', profile_update, name="profile_update"),
    # url(r'^order/(\d+)$', order_detail, name="order_detail"),
    # url(r'^address/$', site, name="address"),
    # url(r'^logout/$', logout, name="logout"),
]

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
  <!--== Start Page Breadcrumb ==-->
<div class="page-breadcrumb-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-breadcrumb">
                    <ul class="nav">
                        <li><a href="{% url 'product:index' %}">Home</a></li>
                        <li><a href="#" class="active">About Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--== End Page Breadcrumb ==-->

<!--== Page Content Wrapper Start ==-->
<div id="page-content-wrapper">
    <div class="container">
        <!-- About Page Content Start -->
        <div class="row">
            <!-- About Text Start -->
            <div class="col-lg-6 order-last order-lg-first">
                <div class="about-text-wrap">
                    <h2><span>About Us</span>ITECH 2019 Team T</h2>
                    <p>It is our Team Project</p>

                    <p>iCasa is a shopping website for electronic products. We provide the latest and most complete apple products.</p>

                    <p>Any product you are interested in can be searched here.It is equipped with the most cutting-edge technologies and latest trends of apple and can meet the needs of all kinds of people for electronic products.</p>
                </div>
            </div>
            <!-- About Text End -->

            <!-- Location Start -->
            <div class="col-lg-5 col-md-10 m-md-auto ml-auto">
                <h2>Where to Find Us</h2>
                <div class="product-image-title" id="map" >

                </div>
            </div>
            <!-- Location End -->
        </div>
        <!-- About Page Content End -->
    </div>
</div>
<!--== Page Content Wrapper End ==-->

    <!-- Start Google Maps API -->
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 55.8736304, lng: -4.293658,},
          zoom: 16
        });
        var marker = new google.maps.Marker({
            position: {lat: 55.8736304, lng: -4.293658,},
            map: map,
  });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBTy4g0m9EWkQJCDvOGTCrOqGFQo_61zFY&callback=initMap"
    async defer></script>
    <style>
        /* Always define the size of the div
       * element that contains the map. */
      #map {
        height: 400px;
          width: 400px;
      }</style>
    <!-- End Google Maps API -->
{% endblock %}

templates/base.html
{% extends 'base_b.html' %}
{% load staticfiles %}

    <!-- Start PreHeader Area -->
{% block preheader %}
    <div class="preheader-area">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-lg-6">
                    <div class="preheader-contact-info d-flex align-items-center justify-content-between justify-content-md-start">
                        <div class="single-contact-info">
                            <a class="welcome-msg" style="color: #1dd983">
                                <strong>Welcome to iCasa!</strong>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-md-7 col-lg-6 mt-xs-10">
                    {% if user.is_authenticated %}
                    <div class="login_btn fl pull-right" style="color: #d2d2d2;">Hi：<em>{{ user.first_name }} {{ user.last_name}} </em>
                        <span>  &ensp;</span>
                        <em><a href="{% url "account_logout" %}">Logout</a></em>
                        <em>&emsp;</em>
                        <em><a href="{% url 'user:myaccount' %}">My Account</a></em>
                    </div>
                    {% else %}
                    <div class="login_btn fl pull-right">
                        <em><a href="{% url "account_login" %}">Login</a></em>
                        <em> | </em>
                        <em><a href="{% url "account_signup" %}">Sign up</a></em>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
    <!-- End PreHeader Area -->

    <!-- Start Header Middle Area -->
{% block headermiddle %}
    <div class="header-middle-area">
        <div class="container">
            <div class="row">
                <!-- Logo Area Start -->
                <div class="col-4 col-md-2 col-xl-3 m-auto text-center text-lg-left">
                    <a href="{% url 'product:index' %}" class="logo-wrap d-block">
                        <img src="{% static 'assets/img/logo.png' %}" alt="Logo" class="img-fluid"/>
                    </a>
                </div>
                <!-- Logo Area End -->

                <!-- Search Box Area Start -->
                <div class="col-8 col-md-7 col- m-auto ">
                    <div class="search-box-wrap">
                        <p class="search-form d-flex" href="javascript:;" method="get">
                            <input id="searchinput" type="search" name="search" placeholder="Search products here"/>
                            <button class="btn btn-search" onclick="javascript:;">
                                <img src="{% static 'assets/img/icons/icon-search.png' %}"
                                                                alt="Search Icon"/>
                            </button>
                        <p>
                    </div>
                </div>
                        <script>
                            $(function () {

                                $('.btn-search').click(function () {
                                    {#                    alert('ok');#}
                                    {#q = $('#searchinput').val();#}
                                    location.href = '{% url "product:search" %}?q='+$('#searchinput').val()+'&page=1'
                                })
                            })
                        </script>
                <!-- Search Box Area End -->

                <!-- Mini Cart Area Start -->
                <div class="col-12 col-md-3 col-xl-2 m-auto text-center text-lg-right mt-xs-15">
                    {% if guest_cart == 1 %}
                    <div class="minicart-wrapper">
                        <button class="btn btn-minicart" onclick="window.location.href='{% url "cart:cart" %}'">My Cart <sup id="show_count" class="cart-count" >{{ cart_num }}</sup></button>
                    </div>
                    {% endif %}
                </div>
                <!-- Mini Cart Area End -->
            </div>
        </div>
    </div>
{% endblock %}
    <!-- End Header Middle Area -->

    <!-- Start Main Menu Area -->
{% block mainmenu %}
    <div class="navigation-area" id="fixheader">
        <div class="container">
            <div class="row">
                <!-- Categories List Start -->
                <div class="col-10 col-lg-3">
                    <div class="categories-list-wrap">
                        <button class="btn btn-category d-none d-lg-inline-block"><i class="fa fa-bars"></i> Categories
                        </button>
                        <ul class="category-list-menu">
                            <li class="category-item-parent dropdown-show">
                                <a href="/list1_1_1/" class="category-item">
                                    <img src="{% static 'assets/img/icons/iphone.png' %}" alt="iPhone"/>
                                    <span>iPhone</span>
                                </a>
                            </li>

                            <li class="category-item-parent dropdown-show">
                                <a href="/list2_1_1/" class="category-item">
                                    <img src="{% static 'assets/img/icons/ipad.png' %}" alt="iPad"/>
                                    <span>iPad</span>
                                </a>
                            </li>
                            <li class="category-item-parent">
                                <a href="/list3_1_1/" class="category-item">
                                    <img src="{% static 'assets/img/icons/mac.png' %}" alt="Mac"/>
                                    <span>Mac</span>
                                </a>
                            </li>
                            <li class="category-item-parent">
                                <a href="/list4_1_1/" class="category-item">
                                    <img src="{% static 'assets/img/icons/watch.png' %}" alt="Watch"/>
                                    <span>Watch</span>
                                </a>
                            </li>
                            <li class="category-item-parent">
                                <a href="/list5_1_1/" class="category-item">
                                    <img src="{% static 'assets/img/icons/accessories.png' %}" alt="Accessories"/>
                                    <span>Accessories</span>
                                </a>
                            </li>
                            <li class="category-item-parent">
                                <a href="/list6_1_1/" class="category-item">
                                    <img src="{% static 'assets/img/icons/other.png' %}" alt="Other"/>
                                    <span>Other</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Categories List End -->

                <!-- Main Menu Start -->
                <div class="col-2 col-lg-9 d-none d-lg-block">
                    <div class="main-menu-wrap">
                        <nav class="mainmenu">
                            <ul class="main-navbar clearfix">
                                <li><a href="{% url 'product:index' %}">Home</a></li>
                                <li><a href="{% url 'product:about' %}">About Us</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- Main Menu End -->
            </div>
        </div>
    </div>
    <!-- End Main Menu Area -->
{% endblock %}
</header>

{% block body %}

<!-- Start Product By Category -->
<!-- End Product By Category -->
{% endblock body %}
<!-- Start Category Banner -->
<!-- End Category Banner -->
<!--== Start Brand Carousel Area ==-->
{% block brands %}
<div class="brand-logo-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="brand-logo-carousel owl-carousel">
                    <!-- Single Brand Logo Start -->
                    <div class="single-brand-item">
                        <a href="https://www.apple.com"><img src="{% static 'assets/img/logo-1.png' %}" alt="logo1"></a>
                    </div>
                    <!-- Single Brand Logo End -->

                    <!-- Single Brand Logo Start -->
                    <div class="single-brand-item">
                        <a href="https://www.gla.ac.uk/"><img src="{% static 'assets/img/logo-2.png' %}" alt="logo2"></a>
                    </div>
                    <!-- Single Brand Logo End -->

                    <!-- Single Brand Logo Start -->
                    <div class="single-brand-item">
                        <a href="https://github.com/WangJintaoWJT"><img src="{% static 'assets/img/logo-3.png' %}" alt="logo3"></a>
                    </div>
                    <!-- Single Brand Logo End -->

                    <!-- Single Brand Logo Start -->
                    <div class="single-brand-item">
                        <a href="https://github.com/zhoujunjiedan"><img src="{% static 'assets/img/logo-4.png' %}" alt="logo4"></a>
                    </div>
                    <!-- Single Brand Logo End -->

                    <!-- Single Brand Logo Start -->
                    <div class="single-brand-item">
                        <a href="https://github.com/JoseYan"><img src="{% static 'assets/img/logo-5.png' %}" alt="logo5"></a>
                    </div>
                    <!-- Single Brand Logo End -->

                    <!-- Single Brand Logo Start -->
                    <div class="single-brand-item">
                        <a href="https://github.com/23524005x"><img src="{% static 'assets/img/logo-6.png' %}" alt="logo6"></a>
                    </div>
                    <!-- Single Brand Logo End -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base_b.html
<!DOCTYPE html>
<html lang="zxx">
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="meta description">

    <title>Home</title>

    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>

    <!--=== Favicon ===-->
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.ico' %}" type="image/x-icon"/>

    <!--== Google Fonts ==-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,400i,500,600,700" rel="stylesheet">

    <!--=== Bootstrap CSS ===-->
    <link href="{% static 'assets/css/vendor/bootstrap.min.css' %}" rel="stylesheet">
    <!--=== Font-Awesome CSS ===-->
    <link href="{% static 'assets/css/vendor/font-awesome.css' %}" rel="stylesheet">
    <!--=== Plugins CSS ===-->
    <link href="{% static 'assets/css/plugins.css' %}" rel="stylesheet">
    <!--=== Helper CSS ===-->
    <link href="{% static 'assets/css/helper.min.css' %}" rel="stylesheet">
    <!--=== Main Style CSS ===-->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- Modernizer JS -->
    <script src="{% static 'assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>

    {% block head %}{% endblock head %}
</head>

<body>


<!--== Start Header Section ==-->
<header id="header-area">
    <!-- Start PreHeader Area -->
    {% block preheader %}
    {% endblock %}
    <!-- End PreHeader Area -->

    <!-- Start Header Middle Area -->
{% block headermiddle %}
    <div class="header-middle-area">
        <div class="container">
            <div class="row">
                <!-- Logo Area Start -->
                <div class="col-4 col-md-2 col-xl-3 m-auto text-center text-lg-left">
                    <a href="{% url 'product:index' %}" class="logo-wrap d-block">
                        <img src="{% static 'assets/img/logo.png' %}" alt="Logo" class="img-fluid"/>
                    </a>
                </div>
                <!-- Logo Area End -->
            </div>
        </div>
    </div>
{% endblock %}
    <!-- End Header Middle Area -->
{% block mainmenu %}
{% endblock %}
</header>
{% block body %}
    {% block content %}
    {% endblock %}
{% endblock body %}
{% block brands %}
{% endblock %}

<!--== Start Newsletter Area ==-->
<!--== End Newsletter Area ==-->

<!--== Start Footer Area ==-->
<footer id="footer-area">
    <!-- Footer Widget Area Start -->
    <div class="footer-widget-area">
        <div class="container">
            <div class="footer-widget-content">
                <div class="row">
                    <!-- Single Widget-item Start -->
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-widget-item">
                            <h3 class="widget-title">Contact Developers</h3>
                            <div class="widget-body">
                                <div class="contact-info">
                                    <div class="single-contact-info">
                                    <span class="contact-icon">
                                        <i class="fa fa-github-square"></i>
                                    </span>
                                        <a href="https://github.com/JoseYan" class="contact-text">
                                           Jinghua  <strong>Yan</strong>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single Widget-item End -->

                    <!-- Single Widget-item Start -->
                       <div class="col-lg-3 col-sm-6">
                        <div class="single-widget-item">
                            <h3 class="widget-title">&#12288</h3>
                            <div class="widget-body">
                                <div class="contact-info">
                                    <div class="single-contact-info">
                                    <span class="contact-icon">
                                        <i class="fa fa-github-alt"></i>
                                    </span>
                                        <a href="https://github.com/zhoujunjiedan" class="contact-text">
                                            Junjie <strong>Zhou</strong>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single Widget-item End -->
                    <!-- Single Widget-item Start -->
                      <div class="col-lg-3 col-sm-6">
                        <div class="single-widget-item">
                            <h3 class="widget-title">&#12288</h3>
                            <div class="widget-body">
                                <div class="contact-info">
                                    <div class="single-contact-info">
                                    <span class="contact-icon">
                                        <i class="fa fa-github"></i>
                                    </span>
                                        <a href="https://github.com/WangJintaoWJT" class="contact-text">
                                            Jintao <strong>Wang</strong>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single Widget-item End -->
                                        <!-- Single Widget-item Start -->
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-widget-item">
                            <h3 class="widget-title">&#12288</h3>
                            <div class="widget-body">
                                <div class="contact-info">
                                    <div class="single-contact-info">
                                    <span class="contact-icon">
                                        <i class="fa fa-github"></i>
                                    </span>
                                        <a href="https://github.com/2352405x" class="contact-text">
                                            Jing <strong>Xu</strong>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single Widget-item End -->
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Widget Area End -->
    <!-- Footer Bottom Area -->
    <div class="footer-bttom-area">
        <div class="container">
            <div class="row">
                <!-- Copyright Text Area -->
                <div class="col-md-6 m-auto text-center text-md-left order-last order-md-first">
                    <p>Copyright &copy; 2019.ITECH Team T All rights reserved.</p>
                </div>
                <!-- Copyright Text Area -->
            </div>
        </div>
    </div>
    <!-- Footer Bottom Area -->
</footer>
<!--== End Footer Area ==-->
<!-- Scroll to Top Start -->
<a href="#" class="scrolltotop"><i class="fa fa-angle-up"></i></a>
<!-- Scroll to Top End -->
<!--Javascript-->
<!--=== Jquery Min Js ===-->
<script src="{% static 'assets/js/vendor/jquery-3.3.1.min.js' %}"></script>
<!--=== Jquery Migrate Min Js ===-->
<script src="{% static 'assets/js/vendor/jquery-migrate-1.4.1.min.js' %}"></script>
<!--=== Popper Min Js ===-->
<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
<!--=== Bootstrap Min Js ===-->
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
<!--=== Ajax Mail Js ===-->
<script src="{% static 'assets/js/ajax-mail.js' %}"></script>
<!--=== Plugins Min Js ===-->
<script src="{% static 'assets/js/plugins.js' %}"></script>
<!--=== Active Js ===-->
<script src="{% static 'assets/js/active.js' %}"></script>
</body>
</html>